### ISSUE TITLE
Fails to read valid FD21 struxml

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#256]
File in test folder

### Error
System.InvalidOperationException: There is an error in XML document (1086, 124).
 ---> System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
   at System.Guid.TryParseExactD(ReadOnlySpan\`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan\`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderModel.Read35_BarPart(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderModel.Read36_Bar(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderModel.Read154_Entities(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderModel.Read197_Model(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderModel.Read198_database()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at FemDesign.Model.DeserializeFromFilePath(String filePath) in C:\\Temp\\2007_carbon_data\\femdesign-api\\FemDesign.Core\\Model\\Model.cs:line 186

**Comment by andosca** [comment]
@xRadne Can you print the guid?

**Comment by xRadne** [comment]
`ae24b484-9b96-4789-ad18-967e9b58ea2f`

**Comment by xRadne** [comment]
The file (in the test folder) can be opened in FEM-Design without problems

**Comment by andosca** [comment]
Actual guid referenced in exception was `D20-400` (complex section guid reference). This has been fixed in another case.
