### ISSUE TITLE
Delta Beam complex section guid BUG

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#280]
Error
```
System.InvalidOperationException
  HResult=0x80131509
  Message=There is an error in XML document (456, 124).
  Source=FemDesign.Core
  StackTrace:
   at FemDesign.Model.DeserializeFromFilePath(String filePath) in C:\Users\Marco\Documents\GitHub\femdesign-api\FemDesign.Core\Model\Model.cs:line 200
   at FemDesign.Tests.ModelTests.ReadWriteFile() in C:\Users\Marco\Documents\GitHub\femdesign-api\FemDesign.Tests\Model\ModelTests.cs:line 118

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
```

``` xml
		<bar name="B.5" type="beam" guid="d06b8b65-a0c2-4f94-846e-dcfd1e06f1dc" last_change="2022-03-18T08:04:36.000" action="added">
			<bar_part guid="f22fa16d-1acb-46da-ba0a-88bd1adbfb96" last_change="2022-03-18T08:04:36.000" action="added" name="B.5.1" complex_section="D20-300" ecc_calc="true">
				<curve type="line">
					<point x="12" y="10" z="0"></point>
					<point x="16" y="14" z="0"></point>
				</curve>
				<local-y x="-0.707106781186548" y="0.707106781186548" z="0"></local-y>
				<connectivity m_x="true" m_y="true" m_z="true" r_x="true" r_y="true" r_z="true"></connectivity>
				<connectivity m_x="true" m_y="true" m_z="true" r_x="true" r_y="true" r_z="true"></connectivity>
				<eccentricity use_default_physical_alignment="true">
					<analytical x="0" y="0" z="0"></analytical>
					<analytical x="0" y="0" z="0"></analytical>
					<physical x="0" y="0" z="-0.1"></physical>
					<physical x="0" y="0" z="-0.1"></physical>
				</eccentricity>
				<end></end>
			</bar_part>
			<end></end>
		</bar>

```

**Comment by andosca** [comment]
Already implemented #103
